import AppKit
import SwiftUI
import WidgetKit

/// Content-layout snapshots of the actual widget view. This deliberately does
/// not load the widget extension or claim to reproduce the desktop widget host.
@main
struct RenderWidgets {
    @MainActor
    static func main() throws {
        let output = URL(fileURLWithPath: CommandLine.arguments.dropFirst().first ?? "build/visuals", isDirectory: true)
        try FileManager.default.createDirectory(at: output, withIntermediateDirectories: true)
        let app = NSApplication.shared
        app.setActivationPolicy(.prohibited)

        let now = Date(timeIntervalSince1970: floor(Date.now.timeIntervalSince1970))
        let fixtures = fixtureSnapshots(now: now)
        let families: [(String, WidgetFamily, NSSize)] = [
            ("small", .systemSmall, NSSize(width: 170, height: 170)),
            ("medium", .systemMedium, NSSize(width: 360, height: 170)),
            ("large", .systemLarge, NSSize(width: 360, height: 382))
        ]

        for (fixtureName, snapshot) in fixtures {
            for (familyName, family, size) in families {
                for dark in [false, true] {
                    let scheme: ColorScheme = dark ? .dark : .light
                    let appearance = NSAppearance(named: dark ? .darkAqua : .aqua)!
                    let content = CodexUsageViewerWidgetContent(snapshot: snapshot, family: family, referenceDate: now)
                        .padding(16)
                        .frame(width: size.width, height: size.height)
                        .background(Color(nsColor: dark
                                          ? NSColor(calibratedWhite: 0.12, alpha: 1)
                                          : NSColor(calibratedWhite: 0.97, alpha: 1)))
                        .clipShape(RoundedRectangle(cornerRadius: 24, style: .continuous))
                        .environment(\.colorScheme, scheme)

                    let host = NSHostingView(rootView: content)
                    host.appearance = appearance
                    host.frame = NSRect(origin: .zero, size: size)
                    let window = NSWindow(contentRect: host.frame, styleMask: .borderless, backing: .buffered, defer: false)
                    window.appearance = appearance
                    window.contentView = host
                    window.backgroundColor = .clear
                    window.isOpaque = false
                    host.layoutSubtreeIfNeeded()
                    // SwiftUI schedules layout/display work on the main run loop.
                    // The window remains offscreen and never changes focus.
                    RunLoop.main.run(until: Date.now.addingTimeInterval(0.12))
                    host.layoutSubtreeIfNeeded()
                    guard let bitmap = host.bitmapImageRepForCachingDisplay(in: host.bounds) else {
                        throw RenderError.bitmapUnavailable
                    }
                    host.cacheDisplay(in: host.bounds, to: bitmap)
                    guard let png = bitmap.representation(using: .png, properties: [:]) else {
                        throw RenderError.pngUnavailable
                    }
                    let filename = "widget-\(fixtureName)-\(familyName)-\(dark ? "dark" : "light").png"
                    try png.write(to: output.appendingPathComponent(filename))
                    print(filename)
                    window.contentView = nil
                }
            }
        }

        let readme = """
        # Widget content visual fixtures

        Generated by `scripts/render_widgets.sh` at \(now.ISO8601Format()).

        All account names, plans, and usage values in these images are synthetic fixtures. No account credentials or live account data are read by this harness.

        The images render the app's actual `CodexUsageViewerWidgetContent` through `NSHostingView`, with representative small (170 × 170 pt), medium (360 × 170 pt), and large (360 × 382 pt) frames and 16 pt content margins. Both light and dark appearances are included.

        The surrounding neutral rounded surface is a rendering fixture. It is not a reproduction of the macOS desktop widget host's Liquid Glass, wallpaper blending, accented mode, or host-selected content margins. These images validate content layout and semantic appearance only; they do not establish native widget-gallery installation, timeline delivery, account integration, or desktop-host appearance.

        Fixtures:

        - `connected`: three synthetic accounts reporting 58%, 21%, and 77% weekly usage remaining, with 3d12h, 18h30m, and 6d2h until reset. The third account reports weekly usage in its primary slot.
        - `empty`: three unconnected accounts; no usage values are invented.
        - `attention`: the first account is stale, the second has an elapsed weekly reset, and the third needs sign-in. No current allowance is invented.
        - `local-match`: synthetic connected accounts with a fresh matching local identity and a long full name; second account has a session quota but no weekly window, and third has no reset timestamp. The first visible badge reads `Logged In` in medium/large.

        Re-run the script after changing shared styles or widget content. Output images and this file are generated under the ignored `build/visuals/` directory.
        """
        try readme.write(to: output.appendingPathComponent("README.md"), atomically: true, encoding: .utf8)
        print("Rendered \(fixtures.count * families.count * 2) content snapshots in \(output.path)")
    }

    private static func fixtureSnapshots(now: Date) -> [(String, UsageSnapshot)] {
        var connected = UsageSnapshot.preview
        connected.savedAt = now
        for index in connected.accounts.indices {
            connected.accounts[index].updatedAt = now
            connected.accounts[index].buckets[0].secondary?.resetsAt = Int(now.timeIntervalSince1970) + [302_400, 66_600, 525_600][index]
        }
        // Weekly can be primary: the widget must never assume secondary.
        let weekly = connected.accounts[2].buckets[0].secondary
        connected.accounts[2].buckets[0].secondary = connected.accounts[2].buckets[0].primary
        connected.accounts[2].buckets[0].primary = weekly
        var attention = connected
        attention.accounts[0].updatedAt = now.addingTimeInterval(-CodexUsageViewerConstants.staleInterval - 60)
        attention.accounts[1].buckets[0].secondary?.resetsAt = Int(now.timeIntervalSince1970) - 30
        attention.accounts[2].state = .needsSignIn
        var localMatch = connected
        localMatch.localCodexEmail = localMatch.accounts[0].email
        localMatch.localCodexCheckedAt = now
        localMatch.accounts[0].fullName = "Alexandra Weiss-Sommerfeld"
        localMatch.accounts[1].buckets[0].secondary = nil
        localMatch.accounts[2].buckets[0].primary?.resetsAt = nil
        return [
            ("connected", connected),
            ("empty", UsageSnapshot(accounts: AccountSnapshot.emptyAccounts, savedAt: now)),
            ("attention", attention),
            ("local-match", localMatch)
        ]
    }

    private enum RenderError: Error {
        case bitmapUnavailable
        case pngUnavailable
    }
}
