import AppKit
import SwiftUI
import WidgetKit

/// Widget content fixtures; does not exercise the desktop host.
@main
struct RenderWidgets {
    @MainActor
    static func main() throws {
        let output = URL(fileURLWithPath: CommandLine.arguments.dropFirst().first ?? "build/visuals", isDirectory: true)
        try FileManager.default.createDirectory(at: output, withIntermediateDirectories: true)
        let app = NSApplication.shared
        app.setActivationPolicy(.prohibited)

        let now = Date(timeIntervalSince1970: floor(Date.now.timeIntervalSince1970))
        let fixtures = fixtureSnapshots(now: now)
        let families: [(String, WidgetFamily, NSSize)] = [
            ("small", .systemSmall, NSSize(width: 170, height: 170)),
            ("medium", .systemMedium, NSSize(width: 360, height: 170)),
            ("large", .systemLarge, NSSize(width: 360, height: 382))
        ]

        for (fixtureName, snapshot) in fixtures {
            for (familyName, family, size) in families {
                for dark in [false, true] {
                    let scheme: ColorScheme = dark ? .dark : .light
                    let appearance = NSAppearance(named: dark ? .darkAqua : .aqua)!
                    let content = CodexUsageViewerWidgetContent(snapshot: snapshot, family: family, referenceDate: now)
                        .padding(16)
                        .frame(width: size.width, height: size.height)
                        .background(Color(nsColor: dark
                                          ? NSColor(calibratedWhite: 0.12, alpha: 1)
                                          : NSColor(calibratedWhite: 0.97, alpha: 1)))
                        .clipShape(RoundedRectangle(cornerRadius: 24, style: .continuous))
                        .environment(\.colorScheme, scheme)

                    let host = NSHostingView(rootView: content)
                    host.appearance = appearance
                    host.frame = NSRect(origin: .zero, size: size)
                    let window = NSWindow(contentRect: host.frame, styleMask: .borderless, backing: .buffered, defer: false)
                    window.appearance = appearance
                    window.contentView = host
                    window.backgroundColor = .clear
                    window.isOpaque = false
                    host.layoutSubtreeIfNeeded()
                    // Let SwiftUI finish layout while the window stays offscreen.
                    RunLoop.main.run(until: Date.now.addingTimeInterval(0.12))
                    host.layoutSubtreeIfNeeded()
                    guard let bitmap = host.bitmapImageRepForCachingDisplay(in: host.bounds) else {
                        throw RenderError.bitmapUnavailable
                    }
                    host.cacheDisplay(in: host.bounds, to: bitmap)
                    guard let png = bitmap.representation(using: .png, properties: [:]) else {
                        throw RenderError.pngUnavailable
                    }
                    let filename = "widget-\(fixtureName)-\(familyName)-\(dark ? "dark" : "light").png"
                    try png.write(to: output.appendingPathComponent(filename))
                    print(filename)
                    window.contentView = nil
                }
            }
        }

        let readme = """
        # Widget fixtures

        Generated by `scripts/render_widgets.sh` at \(now.ISO8601Format()). Sample data only.

        Small: 170 × 170 pt; medium: 360 × 170; large: 360 × 382. Light/dark appearances, 16 pt margins. These render content through NSHostingView, not the desktop host or its timeline.

        - `connected`: weekly quotas in either slot.
        - `empty`: disconnected accounts.
        - `attention`: stale usage, elapsed reset, and expired login.
        - `local-match`: computer icon, long name, missing weekly quota/reset time.
        - `subscription-tiers`: 100/200/500 labels; middle account logged in.
        - `subscription-fallbacks`: unknown and missing plan names.
        """
        try readme.write(to: output.appendingPathComponent("README.md"), atomically: true, encoding: .utf8)
        print("Rendered \(fixtures.count * families.count * 2) content snapshots in \(output.path)")
    }

    private static func fixtureSnapshots(now: Date) -> [(String, UsageSnapshot)] {
        var connected = UsageSnapshot.preview
        connected.savedAt = now
        for index in connected.accounts.indices {
            connected.accounts[index].updatedAt = now
            connected.accounts[index].buckets[0].secondary?.resetsAt = Int(now.timeIntervalSince1970) + [302_400, 66_600, 525_600][index]
        }
        // Weekly can be primary: the widget must never assume secondary.
        let weekly = connected.accounts[2].buckets[0].secondary
        connected.accounts[2].buckets[0].secondary = connected.accounts[2].buckets[0].primary
        connected.accounts[2].buckets[0].primary = weekly
        var attention = connected
        attention.accounts[0].updatedAt = now.addingTimeInterval(-CodexUsageViewerConstants.staleInterval - 60)
        attention.accounts[1].buckets[0].secondary?.resetsAt = Int(now.timeIntervalSince1970) - 30
        attention.accounts[2].state = .needsSignIn
        var localMatch = connected
        localMatch.localCodexEmail = localMatch.accounts[0].email
        localMatch.localCodexCheckedAt = now
        localMatch.accounts[0].fullName = "Alexandra Weiss-Sommerfeld"
        localMatch.accounts[1].buckets[0].secondary = nil
        localMatch.accounts[2].buckets[0].primary?.resetsAt = nil
        var tiers = connected
        for index in tiers.accounts.indices {
            tiers.accounts[index].plan = ["prolite", "pro", "promax"][index]
        }
        tiers.localCodexEmail = tiers.accounts[1].email
        tiers.localCodexCheckedAt = now
        var fallbacks = connected
        fallbacks.accounts[0].plan = "Enterprise Research"
        fallbacks.accounts[1].plan = "plus"
        fallbacks.accounts[2].plan = nil
        return [
            ("connected", connected),
            ("empty", UsageSnapshot(accounts: AccountSnapshot.emptyAccounts, savedAt: now)),
            ("attention", attention),
            ("local-match", localMatch),
            ("subscription-tiers", tiers),
            ("subscription-fallbacks", fallbacks)
        ]
    }

    private enum RenderError: Error {
        case bitmapUnavailable
        case pngUnavailable
    }
}
