import AppKit
import SwiftUI
import WidgetKit

@main
struct RenderWidgets {
    @MainActor
    static func main() throws {
        let output = URL(fileURLWithPath: CommandLine.arguments.dropFirst().first ?? "build/visuals", isDirectory: true)
        try FileManager.default.createDirectory(at: output, withIntermediateDirectories: true)
        let app = NSApplication.shared
        app.setActivationPolicy(.prohibited)

        let now = Date(timeIntervalSince1970: floor(Date.now.timeIntervalSince1970))
        let fixtures = fixtureSnapshots(now: now)
        let families: [(String, WidgetFamily, NSSize)] = [
            ("small", .systemSmall, NSSize(width: 170, height: 170)),
            ("large", .systemMedium, NSSize(width: 360, height: 170))
        ]

        for (fixtureName, snapshot) in fixtures {
            for (familyName, family, size) in families {
                for dark in [false, true] {
                    let scheme: ColorScheme = dark ? .dark : .light
                    let appearance = NSAppearance(named: dark ? .darkAqua : .aqua)!
                    let content = CodexUsageViewerWidgetContent(snapshot: snapshot, family: family, referenceDate: now)
                        .padding(16)
                        .frame(width: size.width, height: size.height)
                        .background(Color(nsColor: dark
                                          ? NSColor(calibratedWhite: 0.12, alpha: 1)
                                          : NSColor(calibratedWhite: 0.97, alpha: 1)))
                        .clipShape(RoundedRectangle(cornerRadius: 24, style: .continuous))
                        .environment(\.colorScheme, scheme)

                    let host = NSHostingView(rootView: content)
                    host.appearance = appearance
                    host.frame = NSRect(origin: .zero, size: size)
                    let window = NSWindow(contentRect: host.frame, styleMask: .borderless, backing: .buffered, defer: false)
                    window.appearance = appearance
                    window.contentView = host
                    window.backgroundColor = .clear
                    window.isOpaque = false
                    host.layoutSubtreeIfNeeded()
                    // Allow offscreen SwiftUI layout to finish.
                    RunLoop.main.run(until: Date.now.addingTimeInterval(0.12))
                    host.layoutSubtreeIfNeeded()
                    guard let bitmap = host.bitmapImageRepForCachingDisplay(in: host.bounds) else {
                        throw RenderError.bitmapUnavailable
                    }
                    host.cacheDisplay(in: host.bounds, to: bitmap)
                    guard let png = bitmap.representation(using: .png, properties: [:]) else {
                        throw RenderError.pngUnavailable
                    }
                    let filename = "widget-\(fixtureName)-\(familyName)-\(dark ? "dark" : "light").png"
                    try png.write(to: output.appendingPathComponent(filename))
                    print(filename)
                    window.contentView = nil
                }
            }
        }

        let readme = """
        # Widget fixtures

        Generated by `scripts/render_widgets.sh` at \(now.ISO8601Format()).

        Sample data rendered through NSHostingView; no live-account, desktop-host, or timeline verification.
        Small: 170 × 170 pt; Large: 360 × 170 pt. Light and dark appearances.

        Covers weekly quota slots, disconnected/stale/expired accounts, missing data, long names,
        local-account icons, subscription tiers/fallbacks, and zero/unknown/unlimited/expired resources.
        """
        try readme.write(to: output.appendingPathComponent("README.md"), atomically: true, encoding: .utf8)
        print("Rendered \(fixtures.count * families.count * 2) content snapshots in \(output.path)")
    }

    private static func fixtureSnapshots(now: Date) -> [(String, UsageSnapshot)] {
        var connected = UsageSnapshot.preview
        connected.savedAt = now
        for index in connected.accounts.indices {
            connected.accounts[index].updatedAt = now
            connected.accounts[index].buckets[0].secondary?.resetsAt = Int(now.timeIntervalSince1970) + [302_400, 66_600, 525_600][index]
        }
        // Weekly quotas may be in either slot.
        let weekly = connected.accounts[2].buckets[0].secondary
        connected.accounts[2].buckets[0].secondary = connected.accounts[2].buckets[0].primary
        connected.accounts[2].buckets[0].primary = weekly
        var attention = connected
        attention.accounts[0].updatedAt = now.addingTimeInterval(-CodexUsageViewerConstants.staleInterval - 60)
        attention.accounts[1].buckets[0].secondary?.resetsAt = Int(now.timeIntervalSince1970) - 30
        attention.accounts[2].state = .needsSignIn
        var localMatch = connected
        localMatch.localCodexEmail = localMatch.accounts[0].email
        localMatch.localCodexCheckedAt = now
        localMatch.accounts[0].fullName = "Alexandra Weiss-Sommerfeld"
        localMatch.accounts[1].buckets[0].secondary = nil
        localMatch.accounts[2].buckets[0].primary?.resetsAt = nil
        var tiers = connected
        for index in tiers.accounts.indices {
            tiers.accounts[index].plan = ["prolite", "pro", "promax"][index]
        }
        tiers.localCodexEmail = tiers.accounts[1].email
        tiers.localCodexCheckedAt = now
        var fallbacks = connected
        fallbacks.accounts[0].plan = "Enterprise Research"
        fallbacks.accounts[1].plan = "plus"
        fallbacks.accounts[2].plan = nil
        var resourceStates = connected
        resourceStates.accounts[0].buckets[0].credits = CreditBalance(hasCredits: false, unlimited: false, balance: "0")
        resourceStates.accounts[0].resetCredits = RateLimitResetCredits(availableCount: 0)
        resourceStates.accounts[1].buckets[0].credits = nil
        resourceStates.accounts[1].resetCredits = nil
        resourceStates.accounts[2].buckets[0].credits = CreditBalance(hasCredits: true, unlimited: false, balance: nil)
        resourceStates.accounts[2].resetCredits = RateLimitResetCredits(availableCount: nil)
        var resourceExtremes = connected
        resourceExtremes.localCodexEmail = resourceExtremes.accounts[0].email
        resourceExtremes.localCodexCheckedAt = now
        resourceExtremes.accounts[0].fullName = "Alexandra Weiss-Sommerfeld"
        resourceExtremes.accounts[0].buckets[0].credits = CreditBalance(hasCredits: true, unlimited: true, balance: nil)
        resourceExtremes.accounts[0].resetCredits = RateLimitResetCredits(availableCount: 1_000)
        resourceExtremes.accounts[1].buckets[0].credits = CreditBalance(hasCredits: true, unlimited: false, balance: "1234567.891234")
        resourceExtremes.accounts[1].resetCredits = RateLimitResetCredits(availableCount: 999_999)
        resourceExtremes.accounts[2].buckets[0].credits = CreditBalance(hasCredits: true, unlimited: false, balance: "0.125476207")
        resourceExtremes.accounts[2].resetCredits = RateLimitResetCredits(availableCount: 1, earliestExpiresAt: Int(now.timeIntervalSince1970) + 60)
        var resourceExpiry = connected
        resourceExpiry.accounts[0].resetCredits = RateLimitResetCredits(availableCount: 3, earliestExpiresAt: Int(now.timeIntervalSince1970) - 30)
        resourceExpiry.accounts[1].updatedAt = now.addingTimeInterval(-CodexUsageViewerConstants.staleInterval - 60)
        resourceExpiry.accounts[2].issue = "The latest usage update could not be loaded."
        var compactLayout = tiers
        for index in compactLayout.accounts.indices {
            compactLayout.accounts[index].fullName = ["George Stone", "Linda Bell", "Hannes Schmidt"][index]
            compactLayout.accounts[index].plan = ["promax", "promax", "prolite"][index]
            compactLayout.accounts[index].buckets[0].primary = QuotaWindow(
                usedPercent: [5, 100, 0][index], windowDurationMins: 10_080,
                resetsAt: Int(now.timeIntervalSince1970) + [482_400, 496_800, 496_800][index])
            compactLayout.accounts[index].buckets[0].secondary = nil
            compactLayout.accounts[index].buckets[0].credits = CreditBalance(
                hasCredits: index == 0, unlimited: false, balance: index == 0 ? "61300" : "0")
            compactLayout.accounts[index].resetCredits = RateLimitResetCredits(availableCount: [1, 1, 3][index])
        }
        var identityFallbacks = connected
        identityFallbacks.accounts[0].fullName = "Alexanderthegreat Longsurname"
        identityFallbacks.accounts[1].fullName = nil
        identityFallbacks.accounts[1].email = "alexandra.longname@example.com"
        identityFallbacks.accounts[2].fullName = "   \n "
        identityFallbacks.accounts[2].email = nil
        var columnExtremes = compactLayout
        for index in columnExtremes.accounts.indices {
            columnExtremes.accounts[index].buckets[0].credits = CreditBalance(
                hasCredits: true, unlimited: false, balance: ["1e30", "999.99", "0.001"][index])
            columnExtremes.accounts[index].resetCredits = RateLimitResetCredits(availableCount: Int.max)
            columnExtremes.accounts[index].buckets[0].primary?.resetsAt = Int(now.timeIntervalSince1970) + [59, 86_340, 604_740][index]
        }
        return [
            ("connected", connected),
            ("empty", UsageSnapshot(accounts: AccountSnapshot.emptyAccounts, savedAt: now)),
            ("attention", attention),
            ("local-match", localMatch),
            ("subscription-tiers", tiers),
            ("subscription-fallbacks", fallbacks),
            ("resource-states", resourceStates),
            ("resource-extremes", resourceExtremes),
            ("resource-expiry", resourceExpiry),
            ("compact-layout", compactLayout),
            ("identity-fallbacks", identityFallbacks),
            ("column-extremes", columnExtremes)
        ]
    }

    private enum RenderError: Error {
        case bitmapUnavailable
        case pngUnavailable
    }
}
